// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vorex.Infrastructure.Persistence;

#nullable disable

namespace Vorex.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250425184639_AddRefreshTokenTable")]
    partial class AddRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CryptoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HoldingDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Risk")
                        .HasPrecision(18, 18)
                        .HasColumnType("decimal(18,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.HasIndex("UserId");

                    b.ToTable("CryptoAnalysisHistories", t =>
                        {
                            t.HasCheckConstraint("CK_CryptoAnalysisHistory_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_CryptoAnalysisHistory_HoldingDays_Positive", "[HoldingDays] > 0");

                            t.HasCheckConstraint("CK_CryptoAnalysisHistory_Risk_Positive", "[Risk] > 0");
                        });
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.Crypto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VolatilityLevelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolatilityLevelID");

                    b.ToTable("Cryptos");
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.HistoricalPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClosingPrice")
                        .HasPrecision(18, 18)
                        .HasColumnType("decimal(18,18)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CryptoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.ToTable("HistoricalPrice", t =>
                        {
                            t.HasCheckConstraint("CK_HistoricalPrice_Month_Valid", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_HistoricalPrice_Year_Valid", "[Year] >= 1 AND [Year] <= 9999");
                        });
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.VolatilityLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("VolatilityLevel");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "low"
                        },
                        new
                        {
                            Id = 1,
                            Name = "medium"
                        },
                        new
                        {
                            Id = 2,
                            Name = "high"
                        });
                });

            modelBuilder.Entity("Vorex.Domain.User.CryptoComparison", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CryptoAnalysisHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("CryptoAnalysisHistoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CryptoAnalysisHistoryId");

                    b.HasIndex("CryptoAnalysisHistoryId");

                    b.HasIndex("CryptoAnalysisHistoryId1");

                    b.ToTable("CryptoComparison");
                });

            modelBuilder.Entity("Vorex.Domain.User.CryptoFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CryptoAnalysisHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("CryptoAnalysisHistoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CryptoAnalysisHistoryId");

                    b.HasIndex("CryptoAnalysisHistoryId");

                    b.HasIndex("CryptoAnalysisHistoryId1");

                    b.ToTable("CryptoFavorite");
                });

            modelBuilder.Entity("Vorex.Domain.User.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Vorex.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", b =>
                {
                    b.HasOne("Vorex.Domain.Cryptos.Crypto", null)
                        .WithMany()
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vorex.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.Crypto", b =>
                {
                    b.HasOne("Vorex.Domain.Cryptos.VolatilityLevel", "VolatilityLevel")
                        .WithMany()
                        .HasForeignKey("VolatilityLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolatilityLevel");
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.HistoricalPrice", b =>
                {
                    b.HasOne("Vorex.Domain.Cryptos.Crypto", null)
                        .WithMany("HistoricalPrices")
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vorex.Domain.User.CryptoComparison", b =>
                {
                    b.HasOne("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", null)
                        .WithMany()
                        .HasForeignKey("CryptoAnalysisHistoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", null)
                        .WithMany("Comparisons")
                        .HasForeignKey("CryptoAnalysisHistoryId1");

                    b.HasOne("Vorex.Domain.User.User", null)
                        .WithMany("Comparisons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vorex.Domain.User.CryptoFavorite", b =>
                {
                    b.HasOne("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", null)
                        .WithMany()
                        .HasForeignKey("CryptoAnalysisHistoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", null)
                        .WithMany("Favorites")
                        .HasForeignKey("CryptoAnalysisHistoryId1");

                    b.HasOne("Vorex.Domain.User.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vorex.Domain.User.RefreshToken", b =>
                {
                    b.HasOne("Vorex.Domain.User.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vorex.Domain.CryptoAnalyses.CryptoAnalysisHistory", b =>
                {
                    b.Navigation("Comparisons");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("Vorex.Domain.Cryptos.Crypto", b =>
                {
                    b.Navigation("HistoricalPrices");
                });

            modelBuilder.Entity("Vorex.Domain.User.User", b =>
                {
                    b.Navigation("Comparisons");

                    b.Navigation("Favorites");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
