<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vorex.Application\Vorex.Application.csproj" />
    <ProjectReference Include="..\Vorex.Domain\Vorex.Domain.csproj" />
  </ItemGroup>

</Project>
